spring:
  cloud:
    kubernetes:
      client:
        namespace: myproject
  application:
    name: helloboot

employee:
  ribbon:
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000
